export const my_blogs = {
    "blog 1": {
        "title": "Why Pouring Salt On Snails Is Cruel & Inhumane",
        "author": "Allan Munene Muchiri",
        "date": "7-01-2024",
        "content":"Pouring salt on a snail is considered cruel and inhumane due to the corrosive and dehydrating effects it has on the creature. Snails, like many other mollusks, have a soft and permeable body. Their skin is not designed to withstand the harsh impact of salt. When salt comes into contact with a snail, it initiates a process known as osmosis. Osmosis involves the movement of water across a semipermeable membrane from an area of low solute concentration to an area of high solute concentration. In this case, the salt creates a hypertonic environment on the snail's skin, causing water to rapidly exit the snail's body. As water is drawn out, the snail experiences severe dehydration, leading to a painful and slow death. The salt essentially acts as a desiccant, disrupting the snail's internal balance and causing irreversible harm. The cruelty lies in the fact that this method of killing a snail is both unnecessary and causes unnecessary suffering. There are more humane ways to address concerns about snails in gardens or unwanted areas without resorting to such a painful method. Using salt to harm these creatures is widely discouraged in ethical and compassionate treatment of animals, promoting alternatives that consider the well-being of all living beings.",
        "image": "/img/slug.jpg" 
    },
    "blog2": {
        "title": "Tardigrades Unearthly Resilience",
        "author": "Khalidi Schlomo",
        "date": "7-01-2024",
        "content":"In the deepest corners of space, where cosmic rays bombard celestial bodies and temperatures fluctuate between extremes, a microscopic miracle quietly unfolds – the incredible resilience of tardigrades, the enigmatic water bears. A team of intrepid scientists embarked on a space exploration mission, sending a payload of these minuscule creatures into the cosmos. Packed within a small capsule, the tardigrades faced the harsh vacuum of space, intense radiation, and the chilling cold of the cosmic void. As the spacecraft traversed the interstellar expanse, the world held its breath, wondering if life, even in its most diminutive form, could withstand the unforgiving conditions beyond our planet. Miraculously, when the capsule returned to Earth, scientists made an astonishing discovery. The tardigrades not only survived the extraterrestrial odyssey but thrived in the face of challenges deemed insurmountable for most life forms. They had endured the vacuum of space, cosmic radiation, and temperature extremes, emerging unscathed, as if they held the secrets to cosmic immortality. Questions echoed through laboratories and observatories alike. How could these micro-organisms, measuring less than a millimeter, withstand the harsh conditions of space that would obliterate larger, seemingly hardier life forms? Scientists delved into the tardigrades' biology, uncovering cryptic mechanisms that allowed them to enter a state of suspended animation, a biological stasis enabling survival in the most hostile environments.The implications were profound, sparking dreams of resilience beyond Earth. Could tardigrades pave the way for preserving life on distant planets or surviving the inhospitable conditions of space travel? As the scientific community marveled at the water bear's extraordinary resilience, a new chapter in space exploration unfolded. Tardigrades, the tiny voyagers, became ambassadors of endurance, challenging our understanding of life's boundaries and offering a glimpse into the possibilities of survival in the vast cosmic tapestry. The water bears, against all odds, continued to defy the limits of what we thought was possible, leaving us to wonder about the extraordinary capabilities hidden within the tiniest threads of life's intricate fabric.",
        "image": "/img/waterbewr.jpg", 
}
}